services:
  gateway:
    image: gateway:latest
    container_name: gateway-dev
    build:
      context: ./gateway/
      dockerfile: Dockerfile.dev
    volumes:
      - ./gateway:/app
    environment:
      - SERVER_ADDR=:8080
      - ENVIRONMENT=dev
    ports:
      - "8080:8080"

  venue-management-service:
    image: venue-management-service:latest
    container_name: venue-management-service-dev
    build:
      context: ./venue-management-service/
      dockerfile: Dockerfile.dev
    volumes:
      - ./venue-management-service:/app
    environment:
      - SERVER_PORT=:8081
      - ENVIRONMENT=dev
    ports:
      - "8081:8081"
