upstream auth_service {
    server auth-service-dev:8082;
}

upstream venue_service {
    server venue-service-dev:8081;
}

upstream communication_service {
    server communication-service-dev:8083;
}
