# syntax=docker/dockerfile:1

FROM golang:1.24.4-alpine

# Set destination for COPY
WORKDIR /app

# Install air and required packages for development
RUN apk add --no-cache curl \
    && go install github.com/air-verse/air@latest

# Add GOPATH/bin to PATH to ensure air is accessible
ENV PATH="/go/bin:${PATH}"

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Optional:
# To bind to a TCP port, runtime parameters must be supplied to the docker command.
# But we can document in the Dockerfile what ports
# the application is going to listen on by default.
# https://docs.docker.com/reference/dockerfile/#expose
EXPOSE 8081

# Run
CMD ["air"]
