FROM golang:1.24.4-alpine

WORKDIR /app

# install air and required packages for development
RUN apk add --no-cache curl git \
  && go install github.com/air-verse/air@latest

# add GOPATH/bin to PATH to ensure air is accessible
ENV PATH="/go/bin:${PATH}"

COPY common/ common/

COPY communication-service/ communication-service/

WORKDIR /app/communication-service

RUN go mod download

# Expose port
EXPOSE 8083

# Run with air for hot reload
CMD ["air"]
