# syntax=docker/dockerfile:1

FROM golang:1.24.4-alpine

ENV GOPRIVATE=github.com/orduro/*

# Set destination for COPY
WORKDIR /app


# Install air and required packages for development
RUN apk add --no-cache curl git \
    && go install github.com/air-verse/air@latest

ARG GITHUB_TOKEN
RUN git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

# Add GOPATH/bin to PATH to ensure air is accessible
ENV PATH="/go/bin:${PATH}"

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Optional:
# To bind to a TCP port, runtime parameters must be supplied to the docker command.
# But we can document in the Dockerfile what ports
# the application is going to listen on by default.
# https://docs.docker.com/reference/dockerfile/#expose
EXPOSE 8081

# Run
CMD ["air"]
