basePath: http://localhost:8080
definitions:
  health.Health:
    properties:
      environment:
        type: string
      health:
        type: string
      service:
        type: string
      timestamp:
        type: string
    type: object
info:
  contact:
    email: austinsofaer@gmail.com
    name: Austin Sofaer (Backend Engineer)
    url: www.linkedin.com/in/austinsofaer
  description: This is the gateway that client's will use to access backend resources
    and services
  title: Gateway API
  version: "1.0"
paths:
  /api/health:
    get:
      consumes:
      - application/json
      description: Get the health status of the gateway service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health.Health'
      summary: Health check endpoint
      tags:
      - health
swagger: "2.0"
